window.TABANJI_LOCALES = window.TABANJI_LOCALES || {};
window.TABANJI_LOCALES.ar = {
  meta: { title: 'تابانجي أوتو — سيارات فاخرة ورياضية خاصة', description: 'اكتشف مجموعة مختارة بعناية من السيارات الفاخرة والرياضية والنادرة لدى تابانجي أوتو.' },
  catalogMeta: { title: 'تابانجي أوتو — مجموعة السيارات الخاصة', description: 'مجموعة مختارة من السيارات الرياضية والفاخرة ذات التاريخ الموثق.' },
  carMeta: { title: 'تفاصيل السيارة — تابانجي أوتو', description: 'تفاصيل سيارة من مجموعة تابانجي أوتو الخاصة.' },
  text: {
    'Головна навігація':'التنقل الرئيسي','Автомобілі':'السيارات','Послуги':'الخدمات','Про нас':'من نحن','Контакти':'اتصل بنا','Зв’язатися':'تواصل معنا','Головна':'الرئيسية','Колекція автомобілів':'مجموعة السيارات','Відібрані спортивні та представницькі автомобілі з підтвердженою історією.':'مجموعة مختارة من السيارات الرياضية والفاخرة ذات التاريخ الموثق.','автомобілів у приватному showroom':'سيارة في صالة العرض الخاصة','Каталог і фільтри':'الكتالوج والفلاتر','знайдено':'نتيجة','Фільтри':'الفلاتر','Сортування':'ترتيب حسب','Рекомендовані':'موصى بها','Нові надходження':'أحدث السيارات','Ціна: від нижчої':'السعر: من الأقل','Ціна: від вищої':'السعر: من الأعلى','Рік: від нового':'السنة: الأحدث أولاً','Пробіг: від меншого':'المسافة: الأقل أولاً','Потужність: від більшої':'القوة: الأعلى أولاً','Сітка':'شبكة','Список':'قائمة','Скинути':'إعادة ضبط','Основні параметри':'المعايير الرئيسية','Пошук':'بحث','Бренд або модель':'العلامة أو الطراز','Бренд':'العلامة','Усі бренди':'جميع العلامات','Модель':'الطراز','Усі моделі':'جميع الطرازات','Статус':'الحالة','Усі статуси':'جميع الحالات','Рік від':'السنة من','Рік до':'السنة إلى','Ціна від':'السعر من','Ціна до':'السعر إلى','Пробіг до, км':'الحد الأقصى للمسافة','Технічні параметри':'المواصفات التقنية','Пальне':'الوقود','Усі типи':'جميع الأنواع','Коробка':'ناقل الحركة','Усі коробки':'جميع نواقل الحركة','Тип кузова':'نوع الهيكل','Усі кузови':'جميع الهياكل','Привід':'نظام الدفع','Потужність від, к.с.':'الحد الأدنى للقوة','Показати':'عرض','Скинути все':'إعادة ضبط الفلاتر','Показати ще':'عرض المزيد','Приватний салон преміальних автомобілів.':'مجموعة سيارات خاصة','Колекція':'المجموعة','Усі автомобілі':'جميع السيارات','Підбір':'توريد خاص','Закрити':'إغلاق','Приватна консультація':'استشارة خاصة','Залиште контакт — персональний менеджер відповість конфіденційно.':'اترك بياناتك وسيتواصل معك مستشار خاص بسرية.','Ім’я *':'الاسم *','Телефон *':'الهاتف *','Бажаний автомобіль':'السيارة المطلوبة','Повідомлення':'الرسالة','Погоджуюся з політикою конфіденційності.':'أوافق على سياسة الخصوصية.','Надіслати запит':'إرسال الطلب','Повернутися нагору':'العودة للأعلى','Навігація':'التنقل','Каталог':'المجموعة',
    'Cars':'السيارات','Services':'الخدمات','About':'من نحن','Contact':'اتصل بنا','Contact Us':'تواصل معنا','Private Automotive Collection':'مجموعة سيارات خاصة','Available':'متاحة','New Arrival':'وصلت حديثاً','Exclusive':'حصرية','Reserved':'محجوزة','Sold':'مباعة','On Request':'حسب الطلب','Details':'التفاصيل','Private Consultation':'استشارة خاصة','Find Similar':'ابحث عن مشابه','No favourites yet':'لا توجد مفضلات بعد','No vehicles found':'لم يتم العثور على سيارات','Add vehicles to your favourites to see them here.':'أضف سيارات إلى المفضلة لتظهر هنا.','Try adjusting or resetting the filters.':'حاول تعديل الفلاتر أو إعادة ضبطها.','Reset Filters':'إعادة ضبط الفلاتر','Show More':'عرض المزيد','Grid':'شبكة','List':'قائمة','Sort by':'ترتيب حسب','Recommended':'موصى بها','Newest arrivals':'أحدث السيارات','Price: Low to High':'السعر: من الأقل إلى الأعلى','Price: High to Low':'السعر: من الأعلى إلى الأقل','Year: Newest first':'السنة: الأحدث أولاً','Mileage: Lowest first':'المسافة: الأقل أولاً','Power: Highest first':'القوة: الأعلى أولاً','Quick View':'عرض سريع','Favourites':'المفضلة','Mode':'الوضع',
    'Cars That Need':'سيارات لا تحتاج','No Introduction':'إلى تعريف','An exclusive selection of performance and luxury automobiles, personally curated by TABANJI AUTO.':'مجموعة حصرية من السيارات الرياضية والفاخرة، مختارة بعناية من تابانجي أوتو.',
    'Explore the Collection':'استكشف المجموعة','Private Consultation':'استشارة خاصة','Model':'الطراز','Power':'القوة','Year':'السنة','Scroll':'مرّر','Explore by marque':'استكشف حسب العلامة',
    'Find a vehicle':'ابحث عن سيارة','Find a Vehicle':'ابحث عن سيارة','Brand':'العلامة','All brands':'جميع العلامات','All models':'جميع الطرازات','Year from':'السنة من','Any year':'أي سنة','Price up to':'السعر حتى','No limit':'بلا حد','Find a Car':'ابحث عن سيارة',
    'Featured Collection':'المجموعة المميزة','A Rare':'مجموعة','Selection':'نادرة','Exceptional specifications with transparent provenance, selected for the private TABANJI collection.':'مواصفات استثنائية ومصدر موثق، مختارة لمجموعة تابانجي الخاصة.',
    'The TABANJI Standard':'معيار تابانجي','Confidence in Every':'ثقة في كل','Detail':'تفصيل','Exacting Selection':'اختيار دقيق','Every vehicle undergoes an expert review of its history, condition and specification.':'تخضع كل سيارة لمراجعة متخصصة لتاريخها وحالتها ومواصفاتها.',
    'Independent Inspection':'فحص مستقل','Complete technical diagnostics and documentary verification before acquisition.':'فحص تقني شامل وتحقق من الوثائق قبل الشراء.','Client Privacy':'خصوصية العميل','A dedicated advisor and complete discretion throughout every stage of the transaction.':'مستشار مخصص وسرية تامة في جميع مراحل الصفقة.','Borderless Delivery':'توصيل بلا حدود','Enclosed logistics, insurance and registration support across international markets.':'نقل مغلق وتأمين ودعم تسجيل عبر الأسواق الدولية.',
    'Private Sourcing':'توريد خاص','Beyond the Open':'ما وراء السوق','Market':'المفتوح','Tell us what you are seeking. TABANJI will source, inspect and deliver it privately.':'أخبرنا بما تبحث عنه، وسنتولى التوريد والفحص والتسليم بخصوصية.','Request Private Sourcing':'اطلب توريداً خاصاً',
    'Our Expertise':'خبراتنا','Service Without':'خدمة بلا','Compromise':'تنازلات','One private advisor coordinates every step, from the first request to the handover of the keys.':'مستشار خاص واحد ينسق كل خطوة من الطلب الأول حتى تسليم المفاتيح.',
    'International Delivery':'توصيل دولي','Trade-In':'استبدال السيارة','Vehicle Inspection':'فحص السيارة','Financing':'التمويل','VIP Concierge':'خدمة كبار العملاء',
    'vehicles delivered':'سيارة تم تسليمها','countries in our network':'دولة ضمن شبكتنا','years of experience':'سنوات من الخبرة','returning clients':'عملاء عائدون',
    'Client Notes':'آراء العملاء','Trust Speaks':'الثقة تتحدث','Quietly':'بهدوء','Your Next Chapter':'فصلك القادم','Your Next Car Should':'يجب أن تكون سيارتك القادمة','Be':'','Exceptional':'استثنائية','Share what you are looking for and your private TABANJI advisor will prepare a tailored proposal.':'شاركنا ما تبحث عنه وسيعد مستشارك الخاص عرضاً مصمماً لك.','View Collection':'عرض المجموعة','Request a Private Consultation':'اطلب استشارة خاصة',
    'Explore':'استكشف','About Us':'من نحن','Beirut, Lebanon':'بيروت، لبنان','Legal':'قانوني','Privacy Policy':'سياسة الخصوصية','Terms of Use':'شروط الاستخدام','Private Luxury & Performance Cars':'سيارات فاخرة ورياضية خاصة',
    'Private Request':'طلب خاص','Leave your details and a private advisor will contact you discreetly.':'اترك بياناتك وسيتواصل معك مستشار خاص بسرية.','Name *':'الاسم *','Phone *':'الهاتف *','Email':'البريد الإلكتروني','Desired Vehicle':'السيارة المطلوبة','Message':'الرسالة','I agree to the Privacy Policy.':'أوافق على سياسة الخصوصية.','Send Request':'إرسال الطلب',
    'Search':'بحث','Show favourites':'عرض المفضلة','Open menu':'فتح القائمة','Close dialog':'إغلاق النافذة','Back to top':'العودة للأعلى','Main navigation':'التنقل الرئيسي','Featured vehicle specifications':'مواصفات السيارة المميزة','Vehicle Not Found':'لم يتم العثور على السيارة','The link does not contain a valid vehicle ID or this vehicle is no longer available.':'الرابط لا يحتوي على معرف صالح أو أن السيارة لم تعد متاحة.','Return to Collection':'العودة إلى المجموعة','Back to Collection':'العودة إلى المجموعة','Contact TABANJI AUTO for verified specifications, provenance and availability.':'تواصل مع تابانجي أوتو للحصول على المواصفات الموثقة وتاريخ السيارة ومدى توفرها.','Request a Private Consultation':'اطلب استشارة خاصة','Year':'السنة','Mileage':'المسافة المقطوعة','Power':'القوة','Engine':'المحرك','Transmission':'ناقل الحركة','Acceleration':'التسارع','Top Speed':'السرعة القصوى','Doors':'الأبواب','Seats':'المقاعد'
  },
  ui: {
    available:'متاحة', new:'وصلت حديثاً', exclusive:'حصرية', reserved:'محجوزة', sold:'مباعة', on_request:'حسب الطلب', petrol:'بنزين', diesel:'ديزل', hybrid:'هجينة', electric:'كهربائية', details:'التفاصيل', allModels:'جميع الطرازات',
    addFavourite:'أضف {model} إلى المفضلة', removeFavourite:'احذف {model} من المفضلة', storageError:'تعذر حفظ المفضلة محلياً في المتصفح.', empty:'لا توجد سيارات مطابقة لهذه المعايير حالياً. يمكننا توفير مواصفاتك المطلوبة بشكل خاص.', found:'تم العثور على {count} {vehicles} في المجموعة الخاصة', vehicle:'سيارة', vehicles:'سيارات', favourites:'المفضلة: {count}', noFavourites:'لم تضف أي سيارة إلى المفضلة بعد', unavailable:'الصورة غير متاحة مؤقتاً', thanks:'شكراً لك. سيتواصل معك مستشارك الخاص قريباً.', leadError:'تم التحقق من طلبك، لكن التخزين المحلي غير متاح. يرجى المحاولة مجدداً.', consultation:'استشارة خاصة', showing:'عرض {shown} من {total}'
  }
};
