window.TABANJI_LOCALES = window.TABANJI_LOCALES || {};
window.TABANJI_LOCALES.en = {
  meta: { title: 'TABANJI AUTO — Private Luxury & Performance Cars', description: 'Discover a privately curated collection of luxury, performance and exotic automobiles from TABANJI AUTO.' },
  catalogMeta: { title: 'TABANJI AUTO — Private Automotive Collection', description: 'A curated selection of performance and luxury automobiles with verified provenance.' },
  carMeta: { title: 'Vehicle — TABANJI AUTO', description: 'Vehicle details from the private TABANJI AUTO collection.' },
  text: {},
  ui: {
    vehicleDetails:'Vehicle Details', vehicleGallery:'Vehicle gallery', vehicleSpecifications:'Vehicle Specifications', vehicleNotFound:'Vehicle Not Found', vehicleNotFoundCopy:'The requested vehicle is unavailable or the link is invalid.', image:'Image', previousImage:'Previous image', nextImage:'Next image', openFullscreen:'Open fullscreen gallery', closeGallery:'Close gallery', imageOf:'Image {x} of {y}', backToCollection:'Back to Collection', price:'Price', description:'Description', keySpecifications:'Key Specifications', mileage:'Mileage', power:'Power', fuel:'Fuel', transmission:'Transmission', acceleration:'Acceleration', topSpeed:'Top Speed', drive:'Drive', bodyType:'Body Type', colour:'Colour', location:'Location', doors:'Doors', seats:'Seats', engine:'Engine', performance:'Performance', ownershipLocation:'Ownership & Location', highlightsEquipment:'Highlights & Equipment', requestThisVehicle:'Request This Vehicle', request:'Request', privateConsultation:'Private Consultation', addToFavourites:'Add to Favourites', removeFromFavourites:'Remove from Favourites', share:'Share', linkCopied:'Link copied', shareUnavailable:'Sharing is unavailable', similarVehicles:'Similar Vehicles', readMore:'Read More', showLess:'Show Less', stockNumber:'Stock', year:'Year', exterior:'Exterior', interior:'Interior', availableOnRequest:'Available on request', bookPrivateViewing:'Book a Private Viewing', requestVideoTour:'Request Video Tour', contactConcierge:'Contact Concierge', whatsappConcierge:'WhatsApp Concierge', whatsappUnavailable:'WhatsApp contact is available through your private advisor', vehicleOverview:'Vehicle Overview', overviewSupport:'Full condition, documentation and provenance details are available during a private consultation.', selectedEquipment:'Selected Equipment', provenanceHistory:'Provenance & History', independentInspection:'Independent inspection', verifiedDocumentation:'Verified documentation', privateTransaction:'Private transaction', enclosedDelivery:'Enclosed delivery',
    openMenu:'Open menu', close:'Close', languageLabel:'Language', english:'English', arabic:'العربية',
    available:'Available', new:'New Arrival', exclusive:'Exclusive', reserved:'Reserved', sold:'Sold', on_request:'On Request', viewDetails:'View Details', openVehicleDetails:'Open details for {model}', quickView:'Quick View', priceOnRequest:'Price on Request',
    petrol:'Petrol', diesel:'Diesel', hybrid:'Hybrid', electric:'Electric', details:'Details', allModels:'All models',
    addFavourite:'Add {model} to favourites', removeFavourite:'Remove {model} from favourites',
    storageError:'The browser could not save your favourites locally.', empty:'No vehicles in the current collection match these parameters. We can source your preferred specification privately.',
    found:'{count} {vehicles} found in the private collection', vehicle:'vehicle', vehicles:'vehicles', favourites:'Favourites: {count}', noFavourites:'You have not added any vehicles to your favourites yet', unavailable:'image temporarily unavailable',
    thanks:'Thank you. Your private advisor will contact you shortly.', leadError:'Your request was validated, but local storage is unavailable. Please try again.', consultation:'Private Consultation', showing:'Showing {shown} of {total}', filter_q:'Search', filter_brand:'Brand', filter_model:'Model', filter_status:'Status', filter_yearMin:'Year From', filter_yearMax:'Year To', filter_priceMin:'Price From', filter_priceMax:'Price To', filter_mileageMax:'Maximum Mileage', filter_fuel:'Fuel', filter_transmission:'Transmission', filter_bodyType:'Body Type', filter_drive:'Drive', filter_powerMin:'Minimum Power', filter_favorites:'Favourites'
  }
};
