window.TABANJI_LOCALES = window.TABANJI_LOCALES || {};
window.TABANJI_LOCALES.ar = {
  meta: { title: 'تابانجي أوتو — سيارات فاخرة ورياضية خاصة', description: 'اكتشف مجموعة مختارة بعناية من السيارات الفاخرة والرياضية والنادرة لدى تابانجي أوتو.' },
  catalogMeta: { title: 'تابانجي أوتو — مجموعة السيارات الخاصة', description: 'مجموعة مختارة من السيارات الرياضية والفاخرة ذات التاريخ الموثق.' },
  carMeta: { title: 'تفاصيل السيارة — تابانجي أوتو', description: 'تفاصيل سيارة من مجموعة تابانجي أوتو الخاصة.' },
  text: {
    'The Automotive Collection':'مجموعة السيارات','A curated selection of performance and luxury automobiles with verified provenance.':'مجموعة مختارة من السيارات الرياضية والفاخرة ذات التاريخ الموثق.','vehicles in the private showroom':'سيارة في صالة العرض الخاصة','Catalog and filters':'الكتالوج والفلاتر','found':'نتيجة','Filters':'الفلاتر','MAIN PARAMETERS':'المعايير الرئيسية','Brand or model':'العلامة أو الطراز','Brand':'العلامة','All brands':'جميع العلامات','Model':'الطراز','All models':'جميع الطرازات','Status':'الحالة','All statuses':'جميع الحالات','Year From':'السنة من','Year To':'السنة إلى','Price From':'السعر من','Price To':'السعر إلى','Maximum Mileage':'الحد الأقصى للمسافة','TECHNICAL PARAMETERS':'المواصفات التقنية','Fuel':'الوقود','All types':'جميع الأنواع','All transmissions':'جميع نواقل الحركة','Body Type':'نوع الهيكل','All body types':'جميع الهياكل','Drive':'نظام الدفع','Minimum Power':'الحد الأدنى للقوة','Show':'عرض','vehicles':'سيارات','Collection':'المجموعة','All Cars':'جميع السيارات','Navigation':'التنقل','Home':'الرئيسية','Breadcrumb':'مسار التنقل','Catalog view':'عرض الكتالوج','Vehicle filters':'فلاتر السيارات','Close filters':'إغلاق الفلاتر','Close':'إغلاق',
    'Cars':'السيارات','Services':'الخدمات','About':'من نحن','Contact':'اتصل بنا','Contact Us':'تواصل معنا','Private Automotive Collection':'مجموعة سيارات خاصة','Available':'متاحة','New Arrival':'وصلت حديثاً','Exclusive':'حصرية','Reserved':'محجوزة','Sold':'مباعة','On Request':'حسب الطلب','Details':'التفاصيل','Private Consultation':'استشارة خاصة','Find Similar':'ابحث عن مشابه','No favourites yet':'لا توجد مفضلات بعد','No vehicles found':'لم يتم العثور على سيارات','Add vehicles to your favourites to see them here.':'أضف سيارات إلى المفضلة لتظهر هنا.','Try adjusting or resetting the filters.':'حاول تعديل الفلاتر أو إعادة ضبطها.','Reset Filters':'إعادة ضبط الفلاتر','Show More':'عرض المزيد','Grid':'شبكة','List':'قائمة','Sort by':'ترتيب حسب','Recommended':'موصى بها','Newest arrivals':'أحدث السيارات','Price: Low to High':'السعر: من الأقل إلى الأعلى','Price: High to Low':'السعر: من الأعلى إلى الأقل','Year: Newest first':'السنة: الأحدث أولاً','Mileage: Lowest first':'المسافة: الأقل أولاً','Power: Highest first':'القوة: الأعلى أولاً','Quick View':'عرض سريع','Favourites':'المفضلة','Mode':'الوضع',
    'Cars That Need':'سيارات لا تحتاج','No Introduction':'إلى تعريف','An exclusive selection of performance and luxury automobiles, personally curated by TABANJI AUTO.':'مجموعة حصرية من السيارات الفاخرة وعالية الأداء، تم اختيارها بعناية من قبل \u2066TABANJI AUTO\u2069.',
    'Explore the Collection':'استكشف المجموعة','Private Consultation':'استشارة خاصة','Model':'الطراز','Power':'القوة','Year':'السنة','Scroll':'مرّر','Explore by marque':'استكشف حسب العلامة',
    'Find a vehicle':'ابحث عن سيارة','Find a Vehicle':'ابحث عن سيارة','Brand':'العلامة','All brands':'جميع العلامات','All models':'جميع الطرازات','Year from':'السنة من','Any year':'أي سنة','Price up to':'السعر حتى','No limit':'بلا حد','Find a Car':'ابحث عن سيارة',
    'Featured Collection':'المجموعة المميزة','A Rare':'مجموعة','Selection':'نادرة','Exceptional specifications with transparent provenance, selected for the private TABANJI collection.':'مواصفات استثنائية ومصدر موثق، مختارة لمجموعة تابانجي الخاصة.',
    'The TABANJI Standard':'معيار تابانجي','Confidence in Every':'ثقة في كل','Detail':'تفصيل','Exacting Selection':'اختيار دقيق','Every vehicle undergoes an expert review of its history, condition and specification.':'تخضع كل سيارة لمراجعة متخصصة لتاريخها وحالتها ومواصفاتها.',
    'Independent Inspection':'فحص مستقل','Complete technical diagnostics and documentary verification before acquisition.':'فحص تقني شامل وتحقق من الوثائق قبل الشراء.','Client Privacy':'خصوصية العميل','A dedicated advisor and complete discretion throughout every stage of the transaction.':'مستشار مخصص وسرية تامة في جميع مراحل الصفقة.','Borderless Delivery':'توصيل بلا حدود','Enclosed logistics, insurance and registration support across international markets.':'نقل مغلق وتأمين ودعم تسجيل عبر الأسواق الدولية.',
    'Private Sourcing':'توريد خاص','Beyond the Open':'ما وراء السوق','Market':'المفتوح','Tell us what you are seeking. TABANJI will source, inspect and deliver it privately.':'أخبرنا بما تبحث عنه، وسنتولى التوريد والفحص والتسليم بخصوصية.','Request Private Sourcing':'اطلب توريداً خاصاً',
    'Our Expertise':'خبراتنا','Service Without':'خدمة بلا','Compromise':'تنازلات','One private advisor coordinates every step, from the first request to the handover of the keys.':'مستشار خاص واحد ينسق كل خطوة من الطلب الأول حتى تسليم المفاتيح.',
    'International Delivery':'توصيل دولي','Trade-In':'استبدال السيارة','Vehicle Inspection':'فحص السيارة','Financing':'التمويل','VIP Concierge':'خدمة كبار العملاء',
    'vehicles delivered':'سيارة تم تسليمها','countries in our network':'دولة ضمن شبكتنا','years of experience':'سنوات من الخبرة','returning clients':'عملاء عائدون',
    'Client Notes':'آراء العملاء','Trust Speaks':'الثقة تتحدث','Quietly':'بهدوء','Your Next Chapter':'فصلك القادم','Your Next Car Should':'يجب أن تكون سيارتك القادمة','Be':'','Exceptional':'استثنائية','Share what you are looking for and your private TABANJI advisor will prepare a tailored proposal.':'شاركنا ما تبحث عنه وسيعد مستشارك الخاص عرضاً مصمماً لك.','View Collection':'عرض المجموعة','Request a Private Consultation':'اطلب استشارة خاصة',
    'Explore':'استكشف','About Us':'من نحن','Beirut, Lebanon':'بيروت، لبنان','Legal':'قانوني','Privacy Policy':'سياسة الخصوصية','Terms of Use':'شروط الاستخدام','Private Luxury & Performance Cars':'سيارات فاخرة ورياضية خاصة',
    'Private Request':'طلب خاص','Leave your details and a private advisor will contact you discreetly.':'اترك بياناتك وسيتواصل معك مستشار خاص بسرية.','Name *':'الاسم *','Phone *':'الهاتف *','Email':'البريد الإلكتروني','Desired Vehicle':'السيارة المطلوبة','Message':'الرسالة','I agree to the Privacy Policy.':'أوافق على سياسة الخصوصية.','Send Request':'إرسال الطلب',
    'Search':'بحث','Show favourites':'عرض المفضلة','Open menu':'فتح القائمة','Close dialog':'إغلاق النافذة','Back to top':'العودة للأعلى','Main navigation':'التنقل الرئيسي','Featured vehicle specifications':'مواصفات السيارة المميزة','Vehicle Not Found':'لم يتم العثور على السيارة','The link does not contain a valid vehicle ID or this vehicle is no longer available.':'الرابط لا يحتوي على معرف صالح أو أن السيارة لم تعد متاحة.','Return to Collection':'العودة إلى المجموعة','Back to Collection':'العودة إلى المجموعة','Contact TABANJI AUTO for verified specifications, provenance and availability.':'تواصل مع تابانجي أوتو للحصول على المواصفات الموثقة وتاريخ السيارة ومدى توفرها.','Request a Private Consultation':'اطلب استشارة خاصة','Year':'السنة','Mileage':'المسافة المقطوعة','Power':'القوة','Engine':'المحرك','Transmission':'ناقل الحركة','Acceleration':'التسارع','Top Speed':'السرعة القصوى','Doors':'الأبواب','Seats':'المقاعد'
  },
  ui: {
    openMenu:'\u0641\u062a\u062d \u0627\u0644\u0642\u0627\u0626\u0645\u0629', close:'\u0625\u063a\u0644\u0627\u0642', languageLabel:'\u0627\u0644\u0644\u063a\u0629', english:'English', arabic:'\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
    available:'متاحة', new:'وصلت حديثاً', exclusive:'حصرية', reserved:'محجوزة', sold:'مباعة', on_request:'حسب الطلب', viewDetails:'عرض التفاصيل', quickView:'نظرة سريعة', priceOnRequest:'السعر عند الطلب', petrol:'بنزين', diesel:'ديزل', hybrid:'هجينة', electric:'كهربائية', details:'التفاصيل', allModels:'جميع الطرازات',
    addFavourite:'أضف {model} إلى المفضلة', removeFavourite:'احذف {model} من المفضلة', storageError:'تعذر حفظ المفضلة محلياً في المتصفح.', empty:'لا توجد سيارات مطابقة لهذه المعايير حالياً. يمكننا توفير مواصفاتك المطلوبة بشكل خاص.', found:'تم العثور على {count} {vehicles} في المجموعة الخاصة', vehicle:'سيارة', vehicles:'سيارات', favourites:'المفضلة: {count}', noFavourites:'لم تضف أي سيارة إلى المفضلة بعد', unavailable:'الصورة غير متاحة مؤقتاً', thanks:'شكراً لك. سيتواصل معك مستشارك الخاص قريباً.', leadError:'تم التحقق من طلبك، لكن التخزين المحلي غير متاح. يرجى المحاولة مجدداً.', consultation:'استشارة خاصة', showing:'عرض {shown} من {total}', filter_q:'بحث', filter_brand:'العلامة', filter_model:'الطراز', filter_status:'الحالة', filter_yearMin:'السنة من', filter_yearMax:'السنة إلى', filter_priceMin:'السعر من', filter_priceMax:'السعر إلى', filter_mileageMax:'الحد الأقصى للمسافة', filter_fuel:'الوقود', filter_transmission:'ناقل الحركة', filter_bodyType:'نوع الهيكل', filter_drive:'نظام الدفع', filter_powerMin:'الحد الأدنى للقوة', filter_favorites:'المفضلة'
  }
};
