window.TABANJI_LOCALES = window.TABANJI_LOCALES || {};
window.TABANJI_LOCALES.en = {
  meta: { title: 'TABANJI AUTO — Private Luxury & Performance Cars', description: 'Discover a privately curated collection of luxury, performance and exotic automobiles from TABANJI AUTO.' },
  catalogMeta: { title: 'TABANJI AUTO — Private Automotive Collection', description: 'A curated selection of performance and luxury automobiles with verified provenance.' },
  carMeta: { title: 'Vehicle — TABANJI AUTO', description: 'Vehicle details from the private TABANJI AUTO collection.' },
  text: {
    'Головна навігація':'Main navigation','Автомобілі':'Cars','Послуги':'Services','Про нас':'About','Контакти':'Contact','Зв’язатися':'Contact Us','Головна':'Home','Колекція автомобілів':'The Automotive Collection','Відібрані спортивні та представницькі автомобілі з підтвердженою історією.':'A curated selection of performance and luxury automobiles with verified provenance.','автомобілів у приватному showroom':'vehicles in the private showroom','Каталог і фільтри':'Catalog and filters','знайдено':'found','Фільтри':'Filters','Сортування':'Sort by','Рекомендовані':'Recommended','Нові надходження':'Newest arrivals','Ціна: від нижчої':'Price: Low to High','Ціна: від вищої':'Price: High to Low','Рік: від нового':'Year: Newest first','Пробіг: від меншого':'Mileage: Lowest first','Потужність: від більшої':'Power: Highest first','Сітка':'Grid','Список':'List','Скинути':'Reset','Основні параметри':'MAIN PARAMETERS','Пошук':'Search','Бренд або модель':'Brand or model','Бренд':'Brand','Усі бренди':'All brands','Модель':'Model','Усі моделі':'All models','Статус':'Status','Усі статуси':'All statuses','Рік від':'Year from','Рік до':'Year to','Ціна від':'Price from','Ціна до':'Price to','Пробіг до, км':'Maximum mileage','Технічні параметри':'TECHNICAL PARAMETERS','Пальне':'Fuel','Усі типи':'All types','Коробка':'Transmission','Усі коробки':'All transmissions','Тип кузова':'Body type','Усі кузови':'All body types','Привід':'Drive','Потужність від, к.с.':'Minimum power','Показати':'Show','Скинути все':'Reset filters','Показати ще':'Show More','Приватний салон преміальних автомобілів.':'Private Automotive Collection','Колекція':'Collection','Усі автомобілі':'All Cars','Підбір':'Private Sourcing','Закрити':'Close','Приватна консультація':'Private Consultation','Залиште контакт — персональний менеджер відповість конфіденційно.':'Leave your details and a private advisor will contact you discreetly.','Ім’я *':'Name *','Телефон *':'Phone *','Бажаний автомобіль':'Desired Vehicle','Повідомлення':'Message','Погоджуюся з політикою конфіденційності.':'I agree to the Privacy Policy.','Надіслати запит':'Send Request','Повернутися нагору':'Back to top','Навігація':'Navigation','Каталог':'Collection'
  },
  ui: {
    available:'Available', new:'New Arrival', exclusive:'Exclusive', reserved:'Reserved', sold:'Sold', on_request:'On Request',
    petrol:'Petrol', diesel:'Diesel', hybrid:'Hybrid', electric:'Electric', details:'Details', allModels:'All models',
    addFavourite:'Add {model} to favourites', removeFavourite:'Remove {model} from favourites',
    storageError:'The browser could not save your favourites locally.', empty:'No vehicles in the current collection match these parameters. We can source your preferred specification privately.',
    found:'{count} {vehicles} found in the private collection', vehicle:'vehicle', vehicles:'vehicles', favourites:'Favourites: {count}', noFavourites:'You have not added any vehicles to your favourites yet', unavailable:'image temporarily unavailable',
    thanks:'Thank you. Your private advisor will contact you shortly.', leadError:'Your request was validated, but local storage is unavailable. Please try again.', consultation:'Private Consultation', showing:'Showing {shown} of {total}'
  }
};
