window.TABANJI_LOCALES = window.TABANJI_LOCALES || {};
window.TABANJI_LOCALES.ar = {
  meta: { title: 'تابانجي أوتو — سيارات فاخرة ورياضية خاصة', description: 'اكتشف مجموعة مختارة بعناية من السيارات الفاخرة والرياضية والنادرة لدى تابانجي أوتو.' },
  text: {
    'Cars':'السيارات','Services':'الخدمات','About':'من نحن','Contact':'اتصل بنا','Contact Us':'اتصل بنا','Private Automotive Collection':'مجموعة سيارات خاصة',
    'Cars That Need':'سيارات لا تحتاج','No Introduction':'إلى تعريف','An exclusive selection of performance and luxury automobiles, personally curated by TABANJI AUTO.':'مجموعة حصرية من السيارات الرياضية والفاخرة، مختارة بعناية من تابانجي أوتو.',
    'Explore the Collection':'استكشف المجموعة','Private Consultation':'استشارة خاصة','Model':'الطراز','Power':'القوة','Year':'السنة','Scroll':'مرّر','Explore by marque':'استكشف حسب العلامة',
    'Find a vehicle':'ابحث عن سيارة','Find a Vehicle':'ابحث عن سيارة','Brand':'العلامة','All brands':'جميع العلامات','All models':'جميع الطرازات','Year from':'السنة من','Any year':'أي سنة','Price up to':'السعر حتى','No limit':'بلا حد','Find a Car':'ابحث عن سيارة',
    'Featured Collection':'المجموعة المميزة','A Rare':'مجموعة','Selection':'نادرة','Exceptional specifications with transparent provenance, selected for the private TABANJI collection.':'مواصفات استثنائية ومصدر موثق، مختارة لمجموعة تابانجي الخاصة.',
    'The TABANJI Standard':'معيار تابانجي','Confidence in Every':'ثقة في كل','Detail':'تفصيل','Exacting Selection':'اختيار دقيق','Every vehicle undergoes an expert review of its history, condition and specification.':'تخضع كل سيارة لمراجعة متخصصة لتاريخها وحالتها ومواصفاتها.',
    'Independent Inspection':'فحص مستقل','Complete technical diagnostics and documentary verification before acquisition.':'فحص تقني شامل وتحقق من الوثائق قبل الشراء.','Client Privacy':'خصوصية العميل','A dedicated advisor and complete discretion throughout every stage of the transaction.':'مستشار مخصص وسرية تامة في جميع مراحل الصفقة.','Borderless Delivery':'توصيل بلا حدود','Enclosed logistics, insurance and registration support across international markets.':'نقل مغلق وتأمين ودعم تسجيل عبر الأسواق الدولية.',
    'Private Sourcing':'توريد خاص','Beyond the Open':'ما وراء السوق','Market':'المفتوح','Tell us what you are seeking. TABANJI will source, inspect and deliver it privately.':'أخبرنا بما تبحث عنه، وسنتولى التوريد والفحص والتسليم بخصوصية.','Request Private Sourcing':'اطلب توريداً خاصاً',
    'Our Expertise':'خبراتنا','Service Without':'خدمة بلا','Compromise':'تنازلات','One private advisor coordinates every step, from the first request to the handover of the keys.':'مستشار خاص واحد ينسق كل خطوة من الطلب الأول حتى تسليم المفاتيح.',
    'International Delivery':'توصيل دولي','Trade-In':'استبدال السيارة','Vehicle Inspection':'فحص السيارة','Financing':'التمويل','VIP Concierge':'خدمة كبار العملاء',
    'vehicles delivered':'سيارة تم تسليمها','countries in our network':'دولة ضمن شبكتنا','years of experience':'سنوات من الخبرة','returning clients':'عملاء عائدون',
    'Client Notes':'آراء العملاء','Trust Speaks':'الثقة تتحدث','Quietly':'بهدوء','Your Next Chapter':'فصلك القادم','Your Next Car Should':'يجب أن تكون سيارتك القادمة','Be':'','Exceptional':'استثنائية','Share what you are looking for and your private TABANJI advisor will prepare a tailored proposal.':'شاركنا ما تبحث عنه وسيعد مستشارك الخاص عرضاً مصمماً لك.','View Collection':'عرض المجموعة','Request a Private Consultation':'اطلب استشارة خاصة',
    'Explore':'استكشف','About Us':'من نحن','Beirut, Lebanon':'بيروت، لبنان','Legal':'قانوني','Privacy Policy':'سياسة الخصوصية','Terms of Use':'شروط الاستخدام','Private Luxury & Performance Cars':'سيارات فاخرة ورياضية خاصة',
    'Private Request':'طلب خاص','Leave your details and a private advisor will contact you discreetly.':'اترك بياناتك وسيتواصل معك مستشار خاص بسرية.','Name *':'الاسم *','Phone *':'الهاتف *','Email':'البريد الإلكتروني','Desired Vehicle':'السيارة المطلوبة','Message':'الرسالة','I agree to the Privacy Policy.':'أوافق على سياسة الخصوصية.','Send Request':'إرسال الطلب',
    'Search':'بحث','Show favourites':'عرض المفضلة','Open menu':'فتح القائمة','Close dialog':'إغلاق النافذة','Back to top':'العودة للأعلى','Main navigation':'التنقل الرئيسي','Featured vehicle specifications':'مواصفات السيارة المميزة'
  },
  ui: {
    available:'متاحة', new:'وصلت حديثاً', exclusive:'حصرية', reserved:'محجوزة', sold:'مباعة', on_request:'حسب الطلب', petrol:'بنزين', diesel:'ديزل', hybrid:'هجينة', electric:'كهربائية', details:'التفاصيل', allModels:'جميع الطرازات',
    addFavourite:'أضف {model} إلى المفضلة', removeFavourite:'احذف {model} من المفضلة', storageError:'تعذر حفظ المفضلة محلياً في المتصفح.', empty:'لا توجد سيارات مطابقة لهذه المعايير حالياً. يمكننا توفير مواصفاتك المطلوبة بشكل خاص.', found:'تم العثور على {count} {vehicles} في المجموعة الخاصة', vehicle:'سيارة', vehicles:'سيارات', favourites:'المفضلة: {count}', noFavourites:'لم تضف أي سيارة إلى المفضلة بعد', unavailable:'الصورة غير متاحة مؤقتاً', thanks:'شكراً لك. سيتواصل معك مستشارك الخاص قريباً.', leadError:'تم التحقق من طلبك، لكن التخزين المحلي غير متاح. يرجى المحاولة مجدداً.', consultation:'استشارة خاصة'
  }
};
